---
- name: deploy nginx aws ingress controllers
  kubernetes.core.helm:
    name: "{{ ingress_name }}"
    chart_ref: ingress-nginx
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_version: "{{ k8s_nginx_chart_release }}"
    release_namespace: "{{ ingress_namespace }}"
    state: "{{ item.value.state }}"
    wait: true
    wait_timeout: "{{ k8s_nginx_wait_timeout }}"
    update_repo_cache: true
    create_namespace: true
    kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
    binary_path: "{{ k8s_helm_bin | default(omit) }}"
    values:
      controller:
        ingressClassResource:
          name: "{{ ingress_class }}"
          controllerValue: "k8s.io/{{ ingress_name }}"
        service:
          external:
            enabled: False
          internal:
            enabled: True
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
              service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
              service.beta.kubernetes.io/aws-load-balancer-type: "external"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "{{ item.value.scheme }}"
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
              service.beta.kubernetes.io/aws-load-balancer-name: "{{ k8s_cluster_name }}-{{ item.key }}"
  vars:
    ingress_class: "nginx-{{ item.value.name }}"
    ingress_name: "{{ item.value.name }}"
    ingress_namespace: "{{ ingress_class }}"
  loop_control:
    label: "{{ item.key }}"
  loop: "{{ k8s_address_pools[k8s_cluster_type] | dict2items }}"
