---
- name: validate pod status
  ansible.builtin.fail:
    msg: "the following pods are in failed status [{{ pod_names | join(', ') }}]"
  vars:
    pod_names: "{{ pods_failed | map(attribute='metadata.name') }}"
    pods_failed: "{{ pod_query | rejectattr('status.phase', 'equalto', 'Running') | rejectattr('status.phase', 'equalto', 'ContainerCreating')}}"
    pod_query: "{{
      query(
        'kubernetes.core.k8s',
        kind='Pod',
        kubeconfig=k8s_kubeconfig
      )
    }}"
  retries: 3
  delay: 60
  until: pods_failed | length == 0
  failed_when: pods_failed | length > 0
