---
- name: Set verification facts
  ansible.builtin.set_fact:
    _query: 'kubernetes.core.k8s'
    _config: "{{ k8s_kubeconfig }}"

- name: Validate pod status
  ansible.builtin.fail:
    msg: "the following pods are in failed status [{{ pods_failed | map(attribute='metadata.name') | join(', ') }}]"
  vars:
    pods_status: "{{ pods_query | selectattr('status', 'defined') }}"
    pods_phase: "{{ pods_status | selectattr('status.phase', 'defined') }}"
    pods_completed: "{{ pods_phase | rejectattr('status.phase', 'equalto', 'Running') }}"
    pods_failed: "{{ pods_completed | rejectattr('status.phase', 'equalto', 'Succeeded') }}"
    pods_query: "{{ query(_query, kind='Pod', kubeconfig=_config) }}"
  retries: "{{ k8s_retry_num }}"
  delay: "{{ k8s_retry_delay }}"
  until: pods_failed | length == 0
  failed_when:
    - (pods_status | length) != (pods_query | length)
    - (pods_phase | length) != (pods_query | length)
    - pods_failed | length > 0
